// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphQL

type DeleteUser struct {
	ID int `json:"id"`
}

type Filter struct {
	Name        *string  `json:"name,omitempty"`
	Surname     *string  `json:"surname,omitempty"`
	Patronymic  *string  `json:"patronymic,omitempty"`
	Age         *int     `json:"age,omitempty"`
	Gender      *string  `json:"gender,omitempty"`
	Nationality []string `json:"nationality"`
}

type FilteredUsers struct {
	Name        string   `json:"name"`
	Surname     string   `json:"surname"`
	Patronymic  *string  `json:"patronymic,omitempty"`
	Age         int      `json:"age"`
	Gender      string   `json:"gender"`
	Nationality []string `json:"nationality"`
}

type ModifyUser struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	Surname     string   `json:"surname"`
	Patronymic  *string  `json:"patronymic,omitempty"`
	Age         int      `json:"age"`
	Gender      string   `json:"gender"`
	Nationality []string `json:"nationality"`
}

type Result struct {
	Success bool         `json:"success"`
	Message *string      `json:"message,omitempty"`
	Error   *ResultError `json:"error,omitempty"`
}

type ResultError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type User struct {
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic,omitempty"`
}
