// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphQL

type DeleteUser struct {
	ID int `json:"id"`
}

type ModifyUser struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	Surname     string   `json:"surname"`
	Patronymic  string   `json:"patronymic"`
	Age         int      `json:"age"`
	Gender      string   `json:"gender"`
	Nationality []string `json:"nationality"`
}

type Result struct {
	Success bool         `json:"success"`
	Message *string      `json:"message,omitempty"`
	Error   *ResultError `json:"error,omitempty"`
}

type ResultError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type User struct {
	Name       string `json:"name"`
	Surname    string `json:"surname"`
	Patronymic string `json:"patronymic"`
}
